title: "club418"
description: "Association pour la promotion du numérique citoyen"
url: "https://club418.github.io"
baseurl: "" # Laisse vide si ton dépôt s'appelle club418.github.io
theme: jekyll-theme-midnight

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock

club418:
  email: "contact@club418.org"
  reseaux:
    twitter: "https://twitter.com/club_418"
    github: "https://github.com/club418"
